### ISSUE TITLE
Remove "See tomorrow's menu" feature

### ISSUE THREAD

**Issue by niehusst** [CSC322-Grinnell/mayflower-dining#41]
On the root page, there is a link that says "see tomorrow's menu". The link appears to correctly load tomorrow's menu from the db, however, it does not change the day highlighted on the calendar widget, and the title text above the menu still says "Today's menu" instead of "Menu for [date]" as it does when you manually click the next day on the calendar.

Fixing this entails updating some html of the span element (id=date) on button click to say the date of the following day, and some js/css stuff to change the active day on the calendar be the day following the td element with class=today

**Comment by XinyaYang0506** [comment]
I want to discuss the usefulness of this feature before we try to fix it.

**Comment by XinyaYang0506** [comment]
Changed this issue to: remove this button and related functions.
