### ISSUE TITLE
white background div not wide enough - ZZZ

### ISSUE THREAD

**Issue by niehusst** [CSC322-Grinnell/mayflower-dining#44]
The background isn't quite wide enough to see the last digit of the phone number (for the width of my screen).

**Comment by niehusst** [comment]
Try to match the mayflowerhomes.com style as closely as possible

**Comment by XinyaYang0506** [comment]
@niehusst @arthurhero  What's your decision on this issue?

**Comment by niehusst** [comment]
I am working on it

**Comment by niehusst** [comment]
defaulted back to Z's original solution, as my rework had worse performance on other machines.
